# Declarative set up (i.e. not with argocd command line)
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/

- name: Register app-of-apps application
  k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: lab
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://github.com/adaptivekind/app-of-apps.git
          targetRevision: HEAD
          path: env/lab
        destination:
          server: https://kubernetes.default.svc
        syncPolicy:
          automated:
            prune: true

- name: Create monitoring namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: monitoring
        labels:
          name: monitoring

- name: Set grafana password
  k8s:
    state: present
    definition:
      apiVersion: v1
      metadata:
        name: grafana-password
        namespace: monitoring
      kind: Secret
      stringData:
        admin-user: admin
        admin-password: "{{ grafana_password }}"
