- name: Set grafana password
  k8s:
    state: present
    definition:
      apiVersion: v1
      metadata:
        name: grafana-password
        namespace: monitoring
      kind: Secret
      stringData:
        admin-user: admin
        admin-password: "{{ grafana_password }}"

- name: Register app-of-apps project
  k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: project-default
        namespace: argocd
        finalizers:
          - resources-finalizer.argocd.argoproj.io
      spec:
        description: default project

        sourceRepos:
          - "*"

        destinations:
          - namespace: "*"
            server: "*"

        clusterResourceWhitelist:
          - group: "*"
            kind: "*"

# Declarative set up (i.e. not with argocd command line)
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/

- name: Register app-of-apps repository
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: app-of-apps-repository
        namespace: argocd
        labels:
          argocd.argoproj.io/secret-type: repository
      stringData:
        type: git
        project: project-default
        url: https://github.com/adaptivekind/app-of-apps.git
        githubAppID: "{{ app_of_apps_github_app_id }}"
        githubAppInstallationID: "{{ app_of_apps_github_installation_id }}"
        githubAppPrivateKey: "{{ app_of_apps_github_private_key | b64decode }}"

- name: Register app-of-apps application
  k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: app-of-app
        namespace: argocd
      spec:
        project: project-default
        source:
          repoURL: https://github.com/adaptivekind/app-of-apps.git
          targetRevision: HEAD
          path: app-of-apps/lab
        destination:
          server: https://kubernetes.default.svc
        syncPolicy:
          automated:
            prune: true
