- copy:
    src: helm.gpg
    dest: /usr/share/keyrings/helm.gpg
  become: true

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=arm64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
    state: present
    update_cache: yes
  become: true

- name: Install helm
  apt:
    name:
      - helm
      - pip
  become: true
