- name: Add ArgoCD repository
  shell: helm repo add argo https://argoproj.github.io/argo-helm

- name: Helm update
  shell: helm repo update

- name: Install python dependencies
  pip:
    name:
      - pyyaml
      - kubernetes
    break_system_packages: true

# - name: Deploy ArgoCD
#   kubernetes.core.helm:
#     name: argocd
#     chart_ref: argo/argo-cd
#     chart_version: 7.6.8
#     release_namespace: argocd
#     create_namespace: true
#     values:
#       configs:
#         cm:
#           timeout.reconciliation: 1800s
#       applicationSet:
#         metrics:
#           enabled: true
#           service:
#             labels:
#               "app.kubernetes.io/name": "argocd-applicationset-controller-metrics"
#       controller:
#         metrics:
#           enabled: true
#       dex:
#         metrics:
#           enabled: true
#       redis:
#         metrics:
#           enabled: true
#           service:
#             labels:
#               "app.kubernetes.io/name": "argocd-redis-metrics"
#       repoServer:
#         metrics:
#           enabled: true
#       server:
#         metrics:
#           enabled: true

- name: Install argocd command
  get_url:
    url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-arm64
    dest: /usr/local/bin/argocd
    mode: "755"
  become: true

- name: Set argocd password
  k8s:
    state: present
    merge_type: merge
    definition:
      apiVersion: v1
      kind: Secret
      data:
        # password encoded with htpasswd -bnBC 10 "" mypassword | tr -d ':\n'
        admin.password: "{{ argocd_encoded_password | b64encode }}"
      metadata:
        namespace: argocd
        name: argocd-secret
