- name: Add ArgoCD repository
  shell: helm repo add argo https://argoproj.github.io/argo-helm

- name: Helm update
  shell: helm repo update

- name: Install python dependencies
  pip:
    name:
      - pyyaml
      - kubernetes
    break_system_packages: true

- name: Deploy ArgoCD
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    values:
      applicationSet:
        metrics:
          enabled: true
          service:
            labels:
              "app.kubernetes.io/name" : "argocd-applicationset-controller-metrics"
      controller:
        metrics:
          enabled: true
      dex:
        metrics:
          enabled: true
      redis:
        metrics:
          enabled: true
          service:
            labels:
              "app.kubernetes.io/name": "argocd-redis-metrics"
      repoServer:
        metrics:
          enabled: true
      server:
        metrics:
          enabled: true

- name: Create route to ArgoCD
  k8s:
    state: present
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: IngressRouteTCP
      metadata:
        name: argocd-route
        namespace: argocd
      spec:
        entryPoints:
          - websecure
        routes:
          - match: HostSNI(`argocd.{{ lab_domain }}`)
            services:
              - name: argocd-server
                port: 443
        tls:
          passthrough: true

# - name: Create web route to ArgoCD
#   k8s:
#     state: present
#     definition:
#       apiVersion: traefik.io/v1alpha1
#       kind: IngressRoute
#       metadata:
#         name: argocd-web-route
#         namespace: argocd
#       spec:
#         routes:
#           - match: Host(`argocd.{{ lab_domain }}`)
#             kind: Rule
#             services:
#               - name: argocd-server
#                 port: 80
#                 namespace: argocd

- name: Create traefik dashboard service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: traefik-dashboard
        namespace: kube-system
        labels:
          app.kubernetes.io/instance: traefik
          app.kubernetes.io/name: traefik-dashboard
      spec:
        type: ClusterIP
        ports:
          - name: traefik
            port: 9000
            targetPort: traefik
            protocol: TCP
        selector:
          app.kubernetes.io/instance: traefik-kube-system
          app.kubernetes.io/name: traefik

- name: Create web route to traefik dashboard
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: traefik-ingress
        namespace: kube-system
        annotations:
          spec.ingressClassName: traefik
      spec:
        rules:
          - host: traefik.{{ lab_domain }}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: traefik-dashboard
                      port:
                        number: 9000

- name: Install argocd command
  get_url:
    url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-arm64
    dest: /usr/local/bin/argocd
    mode: "755"
  become: true
