- copy:
    src: helm.gpg
    dest: /usr/share/keyrings/helm.gpg

- name: Add Docker apt repository
  apt_repository:
    repo: deb [arch=arm64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
    state: present
    update_cache: yes

- name: Install helm
  apt:
    name: helm

- name: Add ArgoCD repository
  shell: helm repo add argo https://argoproj.github.io/argo-helm

- name: Add ArgoCD repository
  shell: helm repo update

- name: Install python dependencies
  pip:
    name:
      - pyyaml
      - kubernetes
    break_system_packages: true

- name: Deploy ArgoCD
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true

- name: Create route to ArgoCD
  k8s:
    state: present
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRouteTCP
      metadata:
        name: argocd-route
        namespace: argocd
      spec:
        entryPoints:
          - websecure
        routes:
          - match: HostSNI(`argocd.{{ lab_domain }}`)
            services:
              - name: argocd-server
                port: 443
        tls:
          passthrough: true
