# Set up encrypted drive
#

- name: Create a new partiion for encrypted drive
  community.general.parted:
    device: /dev/sda
    number: "{{ crypt_device_index }}"
    state: present
    part_start: 90%
    part_end: 100%

- name: Create and open LUKS encrypted device
  community.crypto.luks_device:
    device: "/dev/sda{{ crypt_device_index }}"
    state: opened
    name: crypt
    cipher: "xchacha20,aes-adiantum-plain64"
    hash: sha256
    passphrase: "{{ crypt_passphrase }}"

- name: Create filesystem on LUKS device
  filesystem:
    fstype: ext4
    dev: /dev/mapper/crypt

- name: Ensure the directory /data/ exists
  file:
    path: /data
    state: directory

- name: Mount crypt
  mount:
    path: /data
    src: /dev/mapper/crypt
    state: mounted
    fstype: ext4
