- name: Download go tar file
  command: wget https://go.dev/dl/go{{go_version}}.linux-arm64.tar.gz
  args:
    creates: go{{go_version}}.linux-arm64.tar.gz

- name: Unpack go tar file
  command: tar -C /usr/local -xzf go{{go_version}}.linux-arm64.tar.gz
  args:
    creates: /usr/local/go/bin/go
