- name: Scrape configuration
  k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1alpha1
      kind: ScrapeConfig
      metadata:
        name: exporter-angus
        namespace: monitoring
      spec:
        staticConfigs:
          - targets:
              - 192.168.178.95:9100
        metricsPath: /metrics
