# Set up Docker apt repository as per https://docs.docker.com/engine/install/raspberry-pi-os/
# The GPG key needs to be registered and then the apt repository set up

- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    # The id can be retrieved from
    #    curl https://download.docker.com/linux/raspbian/gpg | gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/raspbian {{ ansible_distribution_release }} stable
    filename: docker

- name: Install Docker
  apt:
    force_apt_get: yes
    name:
      - docker-ce
    install_recommends: no

- name: Add user to docker group
  user:
    name: admin
    append: yes
    groups: docker
  notify: Restart Docker
