- import_playbook: k3s.orchestration.site
  tags: k3s

- name: Initialize lab
  hosts: server
  serial: 1
  collections:
    - ianhomer.lab
  roles:
    - role: cluster_context
      tags: cluster_context
    - role: argocd
      tags: argocd
    - role: app_of_apps
      tags: app_of_apps
