- import_playbook: k3s.orchestration.site
  tags: k3s

- name: Initialize lab
  hosts: server
  serial: 1
  collections:
    - adaptivekind.lab
  roles:
    - role: cluster_storage
      tags: storage
    - role: helm
      tags: helm
    - role: cluster_context
      tags: context
    - role: argocd
      tags: argocd
    - role: app_of_apps
      tags: apps
    - role: cluster_prometheus
      tags: prometheus
    - role: homepage
      tags: homepage
