- name: k3s prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s.orchestration.prereq
    - role: k3s.orchestration.airgap
    - role: k3s.orchestration.raspberrypi
- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s.orchestration.k3s_server
