- name: Initialize prime host
  hosts: prime
  become: yes
  serial: 1
  roles:
    - role: adaptivekind.lab.crypt
      tags: crypt
    - role: adaptivekind.lab.git
      tags: git
    - role: adaptivekind.lab.fileshare
      tags: fileshare
    - role: adaptivekind.lab.go
      tags: go
    - role: adaptivekind.lab.caddy
      tags: caddy
    - role: adaptivekind.lab.docker
      tags: docker
    - role: adaptivekind.lab.pihole
      tags: pihole
    - role: adaptivekind.lab.nfs
      tags: nfs
    - role: adaptivekind.lab.wireguard
      tags: vpn
    - role: adaptivekind.lab.services
      tags: services
