- name: Initialize prime host
  hosts: prime
  become: yes
  serial: 1
  collections:
    - adaptivekind.lab
  roles:
    - role: crypt
      tags: crypt
    - role: git
      tags: git
    - role: go
      tags: go
    - role: caddy
      tags: caddy
    - role: docker
      tags: docker
    - role: pihole
      tags: pihole
    - role: nfs
      tags: nfs
    - role: wireguard
      tags: vpn
    - role: services
      tags: services

