- name: Register services
  template:
    src: "{{ item }}.caddy.j2"
    dest: "/etc/caddy/sites-enabled/{{ item }}.caddy"
  notify: Reload Caddy
  loop: "{{ lab_services }}"

- name: Set up custom DNS list
  template:
    src: custom.list.j2
    dest: /etc/pihole/custom.list
  notify: Restart DNS
