- name: Register services
  template:
    src: "{{ item }}.caddy.j2"
    dest: "/etc/caddy/sites-enabled/{{ item }}.caddy"
  notify: Reload Caddy
  loop: "{{ lab_services }}"

- name: Set up custom DNS list
  template:
    src: custom.list.j2
    dest: /etc/pihole/custom.list
  notify: Restart DNS

- name: Get Cluster CA certificate
  set_fact:
    root_secret: "{{ lookup('k8s', kind='Secret', namespace='cert-manager', resource_name='root-secret') }}"

- copy:
    content="{{ root_secret.data['ca.crt'] | b64decode }}"
    dest=/etc/caddy/certs/cluster-ca.crt
