- name: Get cluster certificate pem
  shell: "openssl s_client -showcerts -connect devon:443 </dev/null 2>/dev/null|openssl x509 -outform PEM > /etc/caddy/cluster.pem"
  args:
    creates: /etc/caddy/cluster.pem

- name: Register ArgoCD service
  template:
    src: argocd.caddy.j2
    dest: /etc/caddy/sites-enabled/argocd.caddy
  notify: Reload Caddy

- name: Register Traefik service
  template:
    src: traefik.caddy.j2
    dest: /etc/caddy/sites-enabled/traefik.caddy
  notify: Reload Caddy

- name: Register Grafana service
  template:
    src: grafana.caddy.j2
    dest: /etc/caddy/sites-enabled/grafana.caddy
  notify: Reload Caddy
