- name: Ensure directory "/etc/pihole" exists
  file:
    path: /etc/pihole/
    state: directory

- name: Set up pi-hole variables
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf

- name: Set up custom DNS list
  template:
    src: custom.list.j2
    dest: /etc/pihole/custom.list
  notify: Restart DNS

- name: Install pihole
  shell: "curl -sSL https://install.pi-hole.net | bash /dev/stdin --unattended"
  args:
    creates: /usr/local/bin/pihole

- name: Set lighttpd port to 8080
  lineinfile:
    path: /etc/lighttpd/lighttpd.conf
    regexp: '^server.port'
    line: 'server.port                 = 8080'
  notify: Reload Lighttpd

- template:
    src: pihole.caddy.j2
    dest: /etc/caddy/sites-enabled/pihole.caddy
  notify: Reload Caddy
